# image: ghcr.io/cirruslabs/flutter
image: flutter/flutter:stable
stages:
  - androidBuild

android:
  stage: androidBuild
  script:
    # - flutter clean 
    - flutter pub get
    - flutter build appbundle --release 
