image : ghcr.io/cirruslabs/flutter:stable

stages :
  - androidBuild

androidBuild :
  stage : androidBuild
  script :
    - $env:Path += ';C:\flutter\bin'
    - $env:ANDROID_SDK_ROOT = "C:\Users\EASHUBH THAPLIYAL\AppData\Local\Android\Sdk"
    # - echo $env:PATH
    - flutter build appbundle --verbose
  tags :
    - flutterandroid