stages:
  - update
  - prepare
  - build
  - deploy
update:
  stage: update
  # only:
  #   - master
  tags:
    - WalkRunner
  script:
   - bundle install 
   - bundle update fastlane
  interruptible: true

create_property_files:
  stage: prepare
  variables: 
    SECURE_FILES_DOWNLOAD_PATH : $pwd
  # only:
  #   - master
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - ls  
    - echo "storeFile=upload-keystore.jks" > key.properties
    - echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
    - echo "keyAlias=$ALIAS" >> key.properties
    - echo "keyPassword=$KEY_PASSWORD" >> key.properties
  artifacts:
    paths:
      - upload-keystore.jks
      - keytest.properties
    expire_in: 10 mins


android:build:
  stage: build
  tags:
    - WalkRunner
  before_script:
    # - fastlane env --capture_output
    - set FLUTTER_PATH= /Users/lifesparktechnologies/Downloads/flutter/bin
    - set ANDROID_SDK_ROOT=/Users/lifesparktechnologies/Documents/Android
  script:
    - cd android
    - fastlane build_android 
  artifacts:
    paths:
    - build/app/outputs/apk/release/app-release.apk
    - build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 week
  interruptible: true

z:internal:android:deploy:
  stage: deploy
  tags:
    - WalkRunner
  script:
    - cd android
    - fastlane deploy_android track:internal
  dependencies:
    - android:build