stages:
  # - update
  - build
  - deploy
# update:
#   stage: update
#   only:
#     - master
#   tags:
#     - WalkAndroidRunner
#   script:
#     - flutter packages get
#     - C:/flutter/bin/flutter packages upgrade
#   interruptible: true

android:build:
  stage: build
  tags:
    - WalkAndroidRunner
  before_script:
    - gem install fastlane  
  script:
    # Flutter local configuration
    - echo flutter.sdk=$FLUTTER_PATH > android/local.properties
    - echo sdk.dir=$ANDROID_SDK_PATH >> android/local.properties
    - echo flutter.buildMode=release >> android/local.properties
    # Android signing
    - echo storePassword=$ANDROID_KEY_STORE_PASSWORD > android/key.properties
    - echo keyPassword=$ANDROID_KEY_PASSWORD >> android/key.properties
    - echo keyAlias=$ANDROID_KEY_ALIAS >> android/key.properties
    - echo storeFile=$ANDROID_KEYSTORE_PATH >> android/key.properties
    - cd android
    - fastlane build_android 
    - rm android/local.properties
    - rm android/key.properties
  artifacts:
    paths:
    - build/app/outputs/apk/release/app-release.apk
    - build/app/outputs/bundle/release/app-rekease.aab
    expire_in: 1 week
  interruptible: true

z:internal:android:deploy:
  stage: deploy
  tags:
    - WalkAndroidRunner
  script:
    - cd android
    - fastlane deploy_android track:internal
  when: manual
  dependencies:
    - android:build