image : ghcr.io/cirruslabs/flutter

stages :
  - androidBuild

androidBuild :
  stage : androidBuild
  script :
    - $env:Path += ';C:\flutter\bin'
    # - echo $env:PATH
    - flutter doctor
  tags :
    - flutterandroid