image: ghcr.io/cirruslabs/flutter
stages:
  - androidBuild
  - androidDeploy

android:
  stage: androidBuild
  script:
    - flutter build apk --release --build-number ${CI_JOB_ID:0:8}
    - flutter build appbundle --release --build-number ${CI_JOB_ID:0:8}
    - bundle install
    - cd android && bundle exec fastlane move_files
  artifacts:
    paths:
      - build/artifacts/
  tags:
    - flutter

playstore:
  stage: androidDeploy
  dependencies:
    - android
  script:
    - cd android && bundle exec fastlane playstore_internal_release
  tags:
    - flutter

