image : ghcr.io/cirruslabs/flutter

stages :
  - androidBuild

androidBuild :
  stage : androidBuild
  before_script:
    - bash reconfigure.sh
  script :
    - flutter build appbundle
  tags :
    - flutterandroid