stages:
  - update
  - prepare
  - build
  - deploy
update:
  stage: update
  only:
    - master
  tags:
    - WalkAndroidRunner
  script:
   - bundle install 
   - bundle update fastlane
  interruptible: true

create_property_files:
  stage: prepare
  variables: 
    SECURE_FILES_DOWNLOAD_PATH : $pwd
  only:
    - master
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    # - Rename-Item upload-keystore.jsk 
    # - echo $KEYSTORE | base64 -d > my.keystore
    - echo "storeFile=upload-keystore.jks" > keytest.properties
    - echo "storePassword=$KEYSTORE_PASSWORD" >> keytest.properties
    - echo "keyAlias=$ALIAS" >> keytest.properties
    - echo "keyPassword=$KEY_PASSWORD" >> keytest.properties
  artifacts:
    paths:
      - upload-keystore.jks
      - keytest.properties
    expire_in: 10 mins


android:build:
  stage: build
  tags:
    - WalkAndroidRunner
  before_script:
    - set FLUTTER_PATH= C:/flutter/bin/flutter
    - set ANDROID_SDK_ROOT=C:/Users/EASHUBH THAPLIYAL/AppData/Local/Android/sdk
    - gem install fastlane  
  script:
    # - echo storePassword=$ANDROID_KEY_STORE_PASSWORD > android/key.properties
    # - echo keyPassword=$ANDROID_KEY_PASSWORD >> android/key.properties
    # - echo keyAlias=$ANDROID_KEY_ALIAS >> android/key.properties
    # - echo storeFile=$ANDROID_KEYSTORE_PATH >> android/key.properties
    - cd android
    - fastlane build_android 
    - rm android/local.properties
    - rm android/key.properties
  artifacts:
    paths:
    - build/app/outputs/apk/release/app-release.apk
    - build/app/outputs/bundle/release/app-rekease.aab
    expire_in: 1 week
  interruptible: true

z:internal:android:deploy:
  stage: deploy
  tags:
    - WalkAndroidRunner
  script:
    - cd android
    - fastlane deploy_android track:internal
  when: manual
  dependencies:
    - android:build