name: walk
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.4+16

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.0.2
  animated_toggle_switch: ^0.6.1
  bluetooth_enable_fork: ^0.1.6
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.0.7
  provider: ^6.0.5
  sleek_circular_slider: ^2.0.1
  wifi_iot: ^0.3.18
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_analytics: ^10.1.4
  # flutter_local_notifications: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  location: ^4.4.0
  multi_select_flutter: ^4.1.3
  pinput: ^2.2.31
  photo_view: ^0.14.0
  image_picker: ^0.8.6
  soundpool: ^2.3.0
  showcaseview: ^1.1.8
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.7
  video_player: ^2.4.9
  wifi_scan: ^0.4.0+1
  http: ^0.13.5
  syncfusion_flutter_charts: ^21.1.38
  fl_chart: ^0.61.0
  path_provider: ^2.0.14
  csv: ^5.0.1
  qr_code_scanner: ^1.0.1
  awesome_ripple_animation: ^1.0.2
  percent_indicator: ^4.2.3
  flutter_background_service: ^3.0.1
  flutter_blue_plus: ^1.20.7
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  rounded_loading_button: ^2.1.0
  flutter_screenutil: ^5.8.4
  rive: ^0.13.1
  flutter_faq: ^1.0.1+1
  awesome_notifications: ^0.7.4+1
  cloud_firestore: ^4.9.1
  firebase_crashlytics: ^3.4.9
  table_calendar: ^3.0.9
  sqflite: ^2.3.2
  connectivity: ^3.0.6
  
  
dependency_overrides:
  watcher: ^1.1.0
  rive: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/tutorial/
    - assets/images/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          style: italic
