name: Install Unity

on:
  push:
    branches:
      - main  # Trigger this workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on PR to main branch

jobs:
  unity-installation:
    runs-on: ubuntu-latest  # You can change this to 'windows-latest' or 'macos-latest' based on your need

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: '2021.3.10f1'  # Replace with your desired Unity version
          activation: 'none'  # No license activation (use 'serial' or 'manual' for Unity Pro)

      - name: Verify Unity installation
        run: |
          unity-editor -version
