name: Unity Build with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unity-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 1: Set up Unity using Docker
      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.47f1' # Replace with your Unity version
          targetPlatform: 'Android'  # Replace with your target platform

      # Step 2: Build Unity Project
      - name: Build Unity Project
        run: |
          unity-editor -quit -batchmode -projectPath ${{ github.workspace }} -executeMethod MyEditorScript.BuildAndroid
